FROM public.ecr.aws/lambda/nodejs:20

WORKDIR ${LAMBDA_TASK_ROOT}

COPY package.json ./

RUN npm install --omit=dev

COPY prisma ./prisma
RUN npx prisma generate --no-engine

COPY src ./src

CMD ["src/handlers/todos/list.handler"]
